// Centralized type definitions for SFIMC
// These match the Payload collection schemas and will eventually be generated by Payload

export interface Member {
  id: string
  name: string
  slug: string
  community: string
  neighborhood?: string
  category: string[]
  description: string
  longDescription?: string
  url: string
  rssUrl?: string
  foundedYear?: number
  color?: string
  logo?: { url: string; alt: string }
  teamPhoto?: { url: string; alt: string }
  socialLinks?: {
    twitter?: string
    facebook?: string
    instagram?: string
  }
  stats?: {
    founded: number
    languages: string[]
    frequency: string
  }
}

export type ImpactType = 'policy' | 'accountability' | 'resources' | 'recognition' | 'community'

export interface Story {
  id: string
  title: string
  slug: string
  excerpt: string
  content?: string
  member: Pick<Member, 'id' | 'name' | 'slug' | 'color'>
  collaborators?: Pick<Member, 'name' | 'slug'>[]
  impactType: ImpactType
  impactDescription: string
  impactTimeline?: { date: string; event: string }[]
  publishedDate: string
  originalUrl?: string
  url: string
  featured?: boolean
  image?: { url: string; alt: string }
}

export interface NewsItem {
  id: string
  guid: string
  title: string
  url: string
  description?: string
  member: Pick<Member, 'name' | 'slug' | 'color'>
  pubDate: string
  image?: { url: string; alt: string }
  promoted?: boolean
}

// Filter/category types
export interface FilterOption {
  value: string
  label: string
}

export interface CategoryFilter extends FilterOption {}
export interface ImpactTypeFilter extends FilterOption {}
export interface MemberFilter extends FilterOption {}
